export const firstNames = [
	'Jazlyn',
	'Justice',
	'Kailee',
	'Shayla',
	'Monserrat',
	'Madalynn',
	'Ryan',
	'Noelle',
	'Lucia',
	'Angelina',
	'Sarai',
	'Sarah',
	'Mollie',
	'Abigail',
	'Leah',
	'Jenny',
	'Jadyn',
	'Areli',
	'Amaris',
	'Isabell',
	'Janelle',
	'Olive',
	'Tiffany',
	'Adeline',
	'Jazlene',
	'Alexia',
	'Serenity',
	'Chaya',
	'Adyson',
	'Lily',
	'Tessa',
	'Mckenna',
	'Britney',
	'Hope',
	'Ashley',
	'Camryn',
	'Luz',
	'Evie',
	'Emmalee',
	'Shea',
	'Makenzie',
	'Skyler',
	'Eden',
	'Allisson',
	'Karly',
	'Amira',
	'Janet',
	'Abbigail',
	'Josie',
	'Shelby',
	'Hector',
	'Triston',
	'Tony',
	'Ashton',
	'Kyan',
	'Dakota',
	'Matias',
	'Karter',
	'Rylee',
	'Efrain',
	'Will',
	'Israel',
	'Hezekiah',
	'Drake',
	'Skyler',
	'Chaz',
	'Josiah',
	'Adrian',
	'Sammy',
	'Elias',
	'Immanuel',
	'Cassius',
	'Nikolas',
	'Brody',
	'Grady',
	'Rene',
	'Kale',
	'Chace',
	'Landyn',
	'Tristan',
	'Jaylin',
	'Gael',
	'Damian',
	'Valentino',
	'Fabian',
	'Davian',
	'Kayden',
	'Kendrick',
	'Kameron',
	'Carter',
	'Isai',
	'Bailey',
	'Chase',
	'Troy',
	'Peyton',
	'Grant',
	'Barrett',
	'Rodolfo',
	'Alijah',
	'Trevor',
];

export const lastNames = [
	'Bowers',
	'Rojas',
	'Shaw',
	'English',
	'Duarte',
	'Wagner',
	'Galvan',
	'Baxter',
	'Ferguson',
	'Kennedy',
	'Tucker',
	'Mason',
	'Cunningham',
	'Hughes',
	'Prince',
	'Brewer',
	'Cross',
	'Fox',
	'Green',
	'May',
	'Hancock',
	'Cherry',
	'Mcdonald',
	'Pham',
	'Castillo',
	'Ross',
	'Novak',
	'Barry',
	'Mccann',
	'Mayo',
	'Patton',
	'Escobar',
	'Wright',
	'Sutton',
	'Cooper',
	'Carey',
	'Thompson',
	'Gilbert',
	'Schultz',
	'Moses',
	'Cordova',
	'Faulkner',
	'Hanna',
	'Santiago',
	'Randall',
	'Schwartz',
	'Huynh',
	'Calderon',
	'Lozano',
	'Payne',
	'Bautista',
	'Beasley',
	'Eaton',
	'Gray',
	'Sandoval',
	'Hopkins',
	'Holt',
	'Robertson',
	'Dyer',
	'West',
	'Johnson',
	'Vasquez',
	'Harding',
	'Reilly',
	'Bush',
	'Cabrera',
	'Robinson',
	'Byrd',
	'Douglas',
	'Ponce',
	'Bray',
	'Singh',
	'Cohen',
	'Diaz',
	'Serrano',
	'Daugherty',
	'Nicholson',
	'Barber',
	'Hart',
	'Glenn',
	'Blackburn',
	'Vaughn',
	'Gonzales',
	'Shepherd',
	'Wiley',
	'Chavez',
	'Luna',
	'Hampton',
	'Dickerson',
	'Wilcox',
	'Pena',
	'Mosley',
	'Dominguez',
	'Sweeney',
	'Lloyd',
	'Oneill',
	'Horn',
	'Grimes',
	'Saunders',
	'Drake',
];

export const majors = [
	'Accounting',
	'Acting',
	'Advertising',
	'Aerospace Engineering',
	'African and African Diaspora Studies',
	'American Studies',
	'Ancient History',
	'Anthropology',
	'Applied Movement Science',
	'Architectural Engineering',
	'Architectural Studies',
	'Architecture',
	'Art Education',
	'Art History',
	'Arts and Entertainment Technologies',
	'Asian Cultures and Languages',
	'Asian Studies',
	'Astronomy',
	'Athletic Training',
	'Biochemistry',
	'Biology ',
	'Biomedical Engineering',
	'Business Administration',
	'Business Analytics',
	'Business Honors Program',
	'Chemical Engineering',
	'Chemistry ',
	'Chinese',
	'Civil Engineering',
	'Classical Archaeology',
	'Classical Languages',
	'Classical Studies',
	'Classics',
	'Communication and Leadership',
	'Communication Studies ',
	'Computational Engineering',
	'Computer Science',
	'Dance',
	'Dance Education',
	'Design',
	'Economics',
	'Education',
	'Electrical and Computer Engineering',
	'English',
	'Environmental Engineering ',
	'Environmental Science',
	'Ethnic Studies ',
	'European Studies',
	'Exercise Science',
	'Finance',
	'French Studies',
	'General Geology',
	'Geography',
	'Geological Sciences',
	'Geophysics',
	'Geosystems Engineering and Hydrogeology',
	'German',
	'Government',
	'Greek',
	'Health & Society',
	'Health Promotion and Behavioral Science',
	'Hindi/Urdu',
	'History',
	'Human Development and Family Sciences ',
	'Human Dimensions of Organizations',
	'Human Ecology',
	'Humanities',
	'Hydrogeology',
	'Informatics',
	'Interior Design',
	'International Business',
	'International Relations and Global Studies',
	'Italian',
	'Japanese',
	'Jazz',
	'Jewish Studies',
	'Journalism',
	'Korean',
	'Latin',
	'Latin American Studies',
	'Linguistics',
	'Malayalam',
	'Management',
	'Management Information Systems',
	'Marketing',
	'Mathematics ',
	'Mechanical Engineering',
	'Medical Laboratory Science',
	'Middle Eastern Studies',
	'Music',
	'Music Composition ',
	'Music Performance',
	'Music Studies',
	'Neuroscience',
	'Nursing',
	'Nutrition ',
	'Petroleum Engineering',
	'Pharmacy',
	'Philosophy',
	'Physical Culture and Sports',
	'Physics ',
	'Plan II Honors Program',
	'Portuguese ',
	'Pre-Pharmacy',
	'Psychology',
	'Public Health',
	'Public Relations',
	'Race, Indigeneity, and Migration',
	'Radio-Television-Film',
	'Religious Studies',
	'Rhetoric and Writing',
	'Russian, East European and Eurasian Studies',
	'Sanskrit',
	'Science and Technology Management',
	'Social Work',
	'Sociology',
	'Spanish',
	'Speech, Language, and Hearing Sciences ',
	'Sport Management',
	'Statistics and Data Science',
	'Studio Art',
	'Supply Chain Management',
	'Sustainability Studies',
	'Tamil',
	'Textiles and Apparel ',
	'Theatre and Dance',
	'Theatre Education',
	'Undeclared (Communication)',
	'Undeclared (Liberal Arts)',
	'Undeclared (Natural Sciences)',
	'Urban Studies',
	'Women’s and Gender Studies',
	'Youth and Community Studies',
];
