-- AlterTable
ALTER TABLE "AuthUser" ADD COLUMN "acceptedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AuthUser" ADD COLUMN "rejectedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AuthUser" ADD COLUMN "waitlistedCount" INTEGER NOT NULL DEFAULT 0;