-- AlterTable
ALTER TABLE "AuthUser" ADD COLUMN IF NOT EXISTS "acceptedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AuthUser" ADD COLUMN IF NOT EXISTS "rejectedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AuthUser" ADD COLUMN IF NOT EXISTS "waitlistedCount" INTEGER NOT NULL DEFAULT 0;
